# Generated by Django 3.2.6 on 2021-08-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarBuds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=255)),
                ('Model_Name', models.CharField(max_length=255)),
                ('Version', models.CharField(max_length=10)),
                ('Noise_Cancellation', models.BooleanField()),
                ('Cost', models.FloatField()),
            ],
        ),
    ]
