# Generated by Django 3.2.6 on 2021-08-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0002_earbuds'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='image_url',
            field=models.CharField(max_length=2083, null=True),
        ),
    ]
